// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteMaster.Server.Data;

#nullable disable

namespace RemoteMaster.Server.Data.Migrations.CrlDbContextMigrations
{
    [DbContext(typeof(CrlDbContext))]
    partial class CrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RemoteMaster.Server.Aggregates.CrlAggregate.Crl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("CertificateRevocationLists");
                });

            modelBuilder.Entity("RemoteMaster.Server.Aggregates.CrlAggregate.RevokedCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CrlId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("RevocationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("CrlId");

                    b.ToTable("RevokedCertificates", (string)null);
                });

            modelBuilder.Entity("RemoteMaster.Server.Aggregates.CrlAggregate.RevokedCertificate", b =>
                {
                    b.HasOne("RemoteMaster.Server.Aggregates.CrlAggregate.Crl", null)
                        .WithMany("RevokedCertificates")
                        .HasForeignKey("CrlId");

                    b.OwnsOne("RemoteMaster.Server.Aggregates.CrlAggregate.ValueObjects.SerialNumber", "SerialNumber", b1 =>
                        {
                            b1.Property<int>("RevokedCertificateId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("SerialNumber")
                                .HasColumnOrder(1);

                            b1.HasKey("RevokedCertificateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("RevokedCertificates");

                            b1.WithOwner()
                                .HasForeignKey("RevokedCertificateId");
                        });

                    b.Navigation("SerialNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("RemoteMaster.Server.Aggregates.CrlAggregate.Crl", b =>
                {
                    b.Navigation("RevokedCertificates");
                });
#pragma warning restore 612, 618
        }
    }
}
