// Copyright © 2023 Vitaly Kuzyaev. All rights reserved.
// This file is part of the RemoteMaster project.
// Licensed under the GNU Affero General Public License v3.0.

using RemoteMaster.Server.Abstractions;
using RemoteMaster.Server.Models;
using RemoteMaster.Shared.Models;

namespace RemoteMaster.Server.Services;

public class CountryProvider : ICountryProvider
{
    public Result<List<Country>> GetCountries()
    {
        var countries = new List<Country>
        {
            new("Afghanistan", "AF"),
            new("Albania", "AL"),
            new("Algeria", "DZ"),
            new("American Samoa", "AS"),
            new("Andorra", "AD"),
            new("Angola", "AO"),
            new("Anguilla", "AI"),
            new("Antarctica", "AQ"),
            new("Antigua and Barbuda", "AG"),
            new("Argentina", "AR"),
            new("Armenia", "AM"),
            new("Aruba", "AW"),
            new("Australia", "AU"),
            new("Austria", "AT"),
            new("Azerbaijan", "AZ"),
            new("Bahamas", "BS"),
            new("Bahrain", "BH"),
            new("Bangladesh", "BD"),
            new("Barbados", "BB"),
            new("Belarus", "BY"),
            new("Belgium", "BE"),
            new("Belize", "BZ"),
            new("Benin", "BJ"),
            new("Bermuda", "BM"),
            new("Bhutan", "BT"),
            new("Bolivia, Plurinational State of", "BO"),
            new("Bonaire, Sint Eustatius and Saba", "BQ"),
            new("Bosnia and Herzegovina", "BA"),
            new("Botswana", "BW"),
            new("Bouvet Island", "BV"),
            new("Brazil", "BR"),
            new("British Indian Ocean Territory", "IO"),
            new("Brunei Darussalam", "BN"),
            new("Bulgaria", "BG"),
            new("Burkina Faso", "BF"),
            new("Burundi", "BI"),
            new("Cabo Verde", "CV"),
            new("Cambodia", "KH"),
            new("Cameroon", "CM"),
            new("Canada", "CA"),
            new("Cayman Islands", "KY"),
            new("Central African Republic", "CF"),
            new("Chad", "TD"),
            new("Chile", "CL"),
            new("China", "CN"),
            new("Christmas Island", "CX"),
            new("Cocos (Keeling) Islands", "CC"),
            new("Colombia", "CO"),
            new("Comoros", "KM"),
            new("Congo", "CG"),
            new("Congo, The Democratic Republic of the", "CD"),
            new("Cook Islands", "CK"),
            new("Costa Rica", "CR"),
            new("Croatia", "HR"),
            new("Cuba", "CU"),
            new("Curaçao", "CW"),
            new("Cyprus", "CY"),
            new("Czechia", "CZ"),
            new("Côte d'Ivoire", "CI"),
            new("Denmark", "DK"),
            new("Djibouti", "DJ"),
            new("Dominica", "DM"),
            new("Dominican Republic", "DO"),
            new("Ecuador", "EC"),
            new("Egypt", "EG"),
            new("El Salvador", "SV"),
            new("Equatorial Guinea", "GQ"),
            new("Eritrea", "ER"),
            new("Estonia", "EE"),
            new("Eswatini", "SZ"),
            new("Ethiopia", "ET"),
            new("Falkland Islands (Malvinas)", "FK"),
            new("Faroe Islands", "FO"),
            new("Fiji", "FJ"),
            new("Finland", "FI"),
            new("France", "FR"),
            new("French Guiana", "GF"),
            new("French Polynesia", "PF"),
            new("French Southern Territories", "TF"),
            new("Gabon", "GA"),
            new("Gambia", "GM"),
            new("Georgia", "GE"),
            new("Germany", "DE"),
            new("Ghana", "GH"),
            new("Gibraltar", "GI"),
            new("Greece", "GR"),
            new("Greenland", "GL"),
            new("Grenada", "GD"),
            new("Guadeloupe", "GP"),
            new("Guam", "GU"),
            new("Guatemala", "GT"),
            new("Guernsey", "GG"),
            new("Guinea", "GN"),
            new("Guinea-Bissau", "GW"),
            new("Guyana", "GY"),
            new("Haiti", "HT"),
            new("Heard Island and McDonald Islands", "HM"),
            new("Holy See (Vatican City State)", "VA"),
            new("Honduras", "HN"),
            new("Hong Kong", "HK"),
            new("Hungary", "HU"),
            new("Iceland", "IS"),
            new("India", "IN"),
            new("Indonesia", "ID"),
            new("Iran, Islamic Republic of", "IR"),
            new("Iraq", "IQ"),
            new("Ireland", "IE"),
            new("Isle of Man", "IM"),
            new("Israel", "IL"),
            new("Italy", "IT"),
            new("Jamaica", "JM"),
            new("Japan", "JP"),
            new("Jersey", "JE"),
            new("Jordan", "JO"),
            new("Kazakhstan", "KZ"),
            new("Kenya", "KE"),
            new("Kiribati", "KI"),
            new("Korea, Democratic People's Republic of", "KP"),
            new("Korea, Republic of", "KR"),
            new("Kuwait", "KW"),
            new("Kyrgyzstan", "KG"),
            new("Lao People's Democratic Republic", "LA"),
            new("Latvia", "LV"),
            new("Lebanon", "LB"),
            new("Lesotho", "LS"),
            new("Liberia", "LR"),
            new("Libya", "LY"),
            new("Liechtenstein", "LI"),
            new("Lithuania", "LT"),
            new("Luxembourg", "LU"),
            new("Macao", "MO"),
            new("Madagascar", "MG"),
            new("Malawi", "MW"),
            new("Malaysia", "MY"),
            new("Maldives", "MV"),
            new("Mali", "ML"),
            new("Malta", "MT"),
            new("Marshall Islands", "MH"),
            new("Martinique", "MQ"),
            new("Mauritania", "MR"),
            new("Mauritius", "MU"),
            new("Mayotte", "YT"),
            new("Mexico", "MX"),
            new("Micronesia, Federated States of", "FM"),
            new("Moldova, Republic of", "MD"),
            new("Monaco", "MC"),
            new("Mongolia", "MN"),
            new("Montenegro", "ME"),
            new("Montserrat", "MS"),
            new("Morocco", "MA"),
            new("Mozambique", "MZ"),
            new("Myanmar", "MM"),
            new("Namibia", "NA"),
            new("Nauru", "NR"),
            new("Nepal", "NP"),
            new("Netherlands", "NL"),
            new("New Caledonia", "NC"),
            new("New Zealand", "NZ"),
            new("Nicaragua", "NI"),
            new("Niger", "NE"),
            new("Nigeria", "NG"),
            new("Niue", "NU"),
            new("Norfolk Island", "NF"),
            new("North Macedonia", "MK"),
            new("Northern Mariana Islands", "MP"),
            new("Norway", "NO"),
            new("Oman", "OM"),
            new("Pakistan", "PK"),
            new("Palau", "PW"),
            new("Palestine, State of", "PS"),
            new("Panama", "PA"),
            new("Papua New Guinea", "PG"),
            new("Paraguay", "PY"),
            new("Peru", "PE"),
            new("Philippines", "PH"),
            new("Pitcairn", "PN"),
            new("Poland", "PL"),
            new("Portugal", "PT"),
            new("Puerto Rico", "PR"),
            new("Qatar", "QA"),
            new("Romania", "RO"),
            new("Russian Federation", "RU"),
            new("Rwanda", "RW"),
            new("Réunion", "RE"),
            new("Saint Barthélemy", "BL"),
            new("Saint Helena, Ascension and Tristan da Cunha", "SH"),
            new("Saint Kitts and Nevis", "KN"),
            new("Saint Lucia", "LC"),
            new("Saint Martin (French part)", "MF"),
            new("Saint Pierre and Miquelon", "PM"),
            new("Saint Vincent and the Grenadines", "VC"),
            new("Samoa", "WS"),
            new("San Marino", "SM"),
            new("Sao Tome and Principe", "ST"),
            new("Saudi Arabia", "SA"),
            new("Senegal", "SN"),
            new("Serbia", "RS"),
            new("Seychelles", "SC"),
            new("Sierra Leone", "SL"),
            new("Singapore", "SG"),
            new("Sint Maarten (Dutch part)", "SX"),
            new("Slovakia", "SK"),
            new("Slovenia", "SI"),
            new("Solomon Islands", "SB"),
            new("Somalia", "SO"),
            new("South Africa", "ZA"),
            new("South Georgia and the South Sandwich Islands", "GS"),
            new("South Sudan", "SS"),
            new("Spain", "ES"),
            new("Sri Lanka", "LK"),
            new("Sudan", "SD"),
            new("Suriname", "SR"),
            new("Svalbard and Jan Mayen", "SJ"),
            new("Sweden", "SE"),
            new("Switzerland", "CH"),
            new("Syrian Arab Republic", "SY"),
            new("Taiwan, Province of China", "TW"),
            new("Tajikistan", "TJ"),
            new("Tanzania, United Republic of", "TZ"),
            new("Thailand", "TH"),
            new("Timor-Leste", "TL"),
            new("Togo", "TG"),
            new("Tokelau", "TK"),
            new("Tonga", "TO"),
            new("Trinidad and Tobago", "TT"),
            new("Tunisia", "TN"),
            new("Turkey", "TR"),
            new("Turkmenistan", "TM"),
            new("Turks and Caicos Islands", "TC"),
            new("Tuvalu", "TV"),
            new("Uganda", "UG"),
            new("Ukraine", "UA"),
            new("United Arab Emirates", "AE"),
            new("United Kingdom", "GB"),
            new("United States", "US"),
            new("United States Minor Outlying Islands", "UM"),
            new("Uruguay", "UY"),
            new("Uzbekistan", "UZ"),
            new("Vanuatu", "VU"),
            new("Venezuela, Bolivarian Republic of", "VE"),
            new("Viet Nam", "VN"),
            new("Virgin Islands, British", "VG"),
            new("Virgin Islands, U.S.", "VI"),
            new("Wallis and Futuna", "WF"),
            new("Western Sahara", "EH"),
            new("Yemen", "YE"),
            new("Zambia", "ZM"),
            new("Zimbabwe", "ZW"),
            new("Åland Islands", "AX")
        };

        return Result<List<Country>>.Success(countries);
    }
}
