// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteMaster.Host.Core.Data;

#nullable disable

namespace RemoteMaster.Host.Core.Data.Migrations.HostDbContextMigrations
{
    [DbContext(typeof(HostDbContext))]
    partial class HostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RemoteMaster.Host.Core.Entities.ConfigurationSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsSyncRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("LastAttempt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("ConfigurationSyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
