name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-container:
    runs-on: ubuntu-latest
    outputs:
      container-status: ${{ steps.start.outputs.container-status }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        compose-file: "./RemoteMaster.Server.Tests/IntegrationTests/docker-compose.yml"
    - name: Set Container Status
      id: start
      run: echo "::set-output name=container-status::success"

  build-and-test:
    runs-on: windows-latest
    needs: start-container

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies for RemoteMaster.Server
      run: |
        cd RemoteMaster.Server
        npm install
        cd ..

    - name: Install .NET dependencies
      run: dotnet restore --ignore-failed-sources --no-cache ./RemoteMaster.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./RemoteMaster.sln

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal ./RemoteMaster.sln
