name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution excluding Windows-specific projects
      run: |
        dotnet sln remove RemoteMaster.Host.Windows/RemoteMaster.Host.Windows.csproj
        dotnet sln remove RemoteMaster.Host.Windows.Tests/RemoteMaster.Host.Windows.Tests.csproj
        dotnet build --no-restore

    - name: Test with coverage for non-Windows projects
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/NonWindows/

    - name: Setup MSBuild for Windows projects
      uses: microsoft/setup-msbuild@v1

    - name: Build and test Windows-specific projects
      run: |
        msbuild RemoteMaster.sln /t:Restore,Build /p:Configuration=Release /p:Platform="Any CPU"
        dotnet test RemoteMaster.Host.Windows.Tests/RemoteMaster.Host.Windows.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Windows/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/**/*.cobertura.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
