name: Secrets Scanning
on:
  push:
    branches: [ master ]
jobs:
  Scan-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Whispers
        run: sudo pip install whispers
      - name: Copy configuration file
        run: cp .github/configs/whispers-config.yml .
      - name: Run scanner for the repository
        run: whispers --config whispers-config.yml ${{ github.workspace }} > /tmp/scan_output.json
      - name: Upload the scan output
        uses: actions/upload-artifact@v3
        with:
          name: scan_results
          path: /tmp/scan_output.json
          retention-days: 2
