// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteMaster.Server.Data;

#nullable disable

namespace RemoteMaster.Server.Data.Migrations
{
    [DbContext(typeof(NodesDbContext))]
    [Migration("20231216070531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RemoteMaster.Shared.Models.Node", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NodeId");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes");

                    b.HasDiscriminator<string>("NodeType").HasValue("Node");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RemoteMaster.Shared.Models.Computer", b =>
                {
                    b.HasBaseType("RemoteMaster.Shared.Models.Node");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "ipAddress");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "macAddress");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("RemoteMaster.Shared.Models.Folder", b =>
                {
                    b.HasBaseType("RemoteMaster.Shared.Models.Node");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("RemoteMaster.Shared.Models.Node", b =>
                {
                    b.HasOne("RemoteMaster.Shared.Models.Node", "Parent")
                        .WithMany("Nodes")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RemoteMaster.Shared.Models.Node", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
